services:
  petplace_backend:
    container_name: petplace-backend
    image: ghcr.io/231031/petplace/petplace_backend:${DOCKER_TAG}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "50001:50001"
    networks:
      - petplace_nw

  petplace_frontend:
    container_name: petplace-frontend
    image: ghcr.io/231031/petplace/petplace_frontend:${DOCKER_TAG}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - petplace_backend
    networks:
      - petplace_nw

networks:
  petplace_nw:
    driver: bridge