# Config file for Air
[build]
cmd = "go build -o cmd/main/main ./cmd/*/*.go"
bin = "./cmd/main/main"
full_bin = "APP_ENV=dev ./cmd/main/main"

# Watch for changes in these file types, but don't rebuild, only re-run the binary
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_ext = ["md", "txt"]

# Ignore these directories since we don't want to monitor these
exclude_dir = ["public", "docs", "migrations"]

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop to run old binary when build errors occur.
stop_on_error = true
log = "air_errors.log"

[log]
time = false
level = "debug"

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

