FROM golang:1.23.1-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN go build -o main ./cmd/main/main.go

RUN chmod +x ./cmd/main/main

EXPOSE 5000

CMD [ "./cmd/main/main" ]