FROM golang:1.23.1-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN go build -o main ./cmd/main

RUN chmod +x ./main

# Expose port
EXPOSE 50001

CMD ["/app/main"]