services:
  nginx:
    container_name: petplace-nginx
    image: nginx:alpine
    ports:
      - 80:80
    build: .
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - petplace_api
      - petplace_db
    networks:
      - petplace_networks

  petplace_api:
    container_name: petplace-api
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./public:/app/go/public
      - ./:/app/go
    depends_on:
      - petplace_db
    networks:
      - petplace_networks

  petplace_db:
    image: mysql
    restart: unless-stopped
    container_name: petplace-db
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    volumes:
      - petplace_volumes:/var/lib/mysql
    networks:
      - petplace_networks

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - petplace_db
    ports:
      - 8081:80
    env_file:
      - .env
    environment:
      - PMA_HOST=${DATABASE_HOST}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    networks:
      - petplace_networks

  petplace_db_test:
    image: mysql
    restart: unless-stopped
    container_name: petplace-db-test
    env_file:
      - .env
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=petplace
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345
      - MYSQL_TCP_PORT=3307
    volumes:
      - petplace_volumes_test:/var/lib/mysql
    networks:
      - petplace_networks

  phpmyadmin_test:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - petplace_db_test
    ports:
      - 8082:80
    env_file:
      - .env
    environment:
      - PMA_HOST=petplace_db_test
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    networks:
      - petplace_networks

networks:
  petplace_networks:
    driver: bridge
volumes:
  petplace_volumes:
  petplace_volumes_test:
