name: Deploy Petplace

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: amazon-linux
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "SECRET_ID=${{ secrets.SECRET_ID }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_API_INFO=${{ variables.GOOGLE_API_INFO }}" >> .env
          echo "GOOGLE_API_INFO=${{ variables.FRONT_URL }}" >> .env

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker all images
        run: docker-compose build
      - name: Push images to docker hub
        run: docker-compose push
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker images
        run: docker-compose pull
      - name: Delete old docker container
        run: docker-compose down
      - name: Run docker container
        run: docker-compose up -d

